# Rename to .streamlit/secrets.toml locally
# and fill in your own tokens → NEVER COMMIT THE REAL ONE!
OPENAI_API_KEY = "your-openai-key-here"
MODEL_NAME     = "gpt-4o-mini"
CHROMA_DIR     = "/tmp/chroma"
